name: radio_ly
description: "良友电台-同行频道"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.1
  flutter_launcher_icons: "^0.13.1"
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  wakelock: ^0.6.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
#flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon.png"
  min_sdk_android: 16
  web:
    generate: true
    image_path: "assets/appIcon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/appIcon.png"
    icon_size: 64 
  macos:
    generate: true
    image_path: "assets/appIcon.png"