on:
  push:
    tags:
      - "v*"
name: Build APK exe ipa linuxBin
jobs:
  build_ios:
    name: build_ios
    runs-on: macos-latest
    permissions:
      contents: write
      discussions: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.5'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign --no-tree-shake-icons
    - run: mkdir build/ios/iphoneos/Payload
    #- run: cp -r --parents build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
    - run: ditto build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
    - run: zip -r -9 build/ios/iphoneos/ios-no-codesign.app.zip build/ios/iphoneos/Payload/
    - run: mv build/ios/iphoneos/ios-no-codesign.app.zip build/ios/iphoneos/ios-no-codesign.ipa
    - name: upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ipa
        path: build/ios/iphoneos/ios-no-codesign.ipa

  build_win:
    name: build_win
    runs-on: windows-latest
    permissions:
      contents: write
      discussions: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.5'
    - run: flutter config --enable-windows-desktop
    - run: flutter pub get
    - run: flutter build windows
    - run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath build\windows\x64\runner\windows_x64_runner.zip
    - name: upload Windows
      uses: actions/upload-artifact@v4
      with:
        name: exe
        path: build/windows/x64/runner/windows_x64_runner.zip

  build_apk:
    name: build_apk
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.5'
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter build apk --no-tree-shake-icons
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: build/app/outputs/apk/release/*.apk

  build_linux:
    name: build_linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.5'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
        sudo apt-get install -y libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev  #音频播放器
        sudo apt-get install -y gstreamer1.0-plugins-good gstreamer1.0-plugins-bad #音频播放器m3u8
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter build linux --no-tree-shake-icons
    - run: zip -r -9 build/linux/x64/release/linux_x64_bundle.zip build/linux/x64/release/bundle
    - name: upload-linux
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: build/linux/x64/release/linux_x64_bundle.zip
  Publish:
    needs: [build_ios, build_win, build_apk,build_linux]
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
              files: |
                ipa/*.ipa
                exe/*.zip
                apk/*.apk
                linux/*.zip
              prerelease: false
