on:
    workflow_dispatch:
name: Build ipad ipa Release 
jobs:
    build:
      name: Build
      runs-on: macos-latest
      permissions:
        contents: write
        discussions: write
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
            flutter-version: '3.16.5'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign --no-tree-shake-icons 
      # 压缩 *.app 为 *.ipa 
      - run: mkdir build/ios/iphoneos/Payload
      - run: cp -r --parents build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
      - run: zip -r -9  build/ios/iphoneos/ios-no-codesign.app.zip build/ios/iphoneos/Payload/
      - run: mv build/ios/iphoneos/ios-no-codesign.app.zip build/ios/iphoneos/ios-no-codesign.ipa
      - name: upload
        uses: actions/upload-artifact@v4
        with:
            name: my-ipa
            path: build/ios/iphoneos/ios-no-codesign.ipa 