on:
    workflow_dispatch:
name: Build linux x64
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
        contents: write
        discussions: write
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.5'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter build linux --no-tree-shake-icons 
    #build/linux/x64/release/bundle/
    - run:  zip -r -9  build/linux/x64/release/linux_x64_bundle.zip build/linux/x64/release/bundle
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: my-linux_x64_bundle
        path: build/linux/x64/release/linux_x64_bundle.zip 
